---
title: "Assembly Comparison Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
toc: true
embed-resources: true
code-fold: true
params:
  #bam_file: "../results/CP047704.1.bam"
  #txt_file: "../results/CP047704.1.txt"
  bam_file: "/Users/prados/Downloads/docker/run1/work/6c/fd40de806a450c73690e9bfd093096/out.bam"
  txt_file: "/Users/prados/Downloads/docker/run1/work/2d/3dec8fe687782e7b3ba80f70cfb785/mutations.txt"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
source("assets/lib_bam.R")
```

# Input Files

|          |                     |
|:---------|---------------------|
| BAM      | `r params$bam_file` | 
| Mutation | `r params$txt_file` |

```{r}
bedpe <- BamFile(params$bam_file) |>
	readGAlignments(bam,use.names = TRUE) |>
	gaCigarBedpe()

muts <- read_tsv(
  params$txt_file,
  col_names = c("chrom", "pos", "change"),
  col_types = cols(pos="i",.default="c")
) |>
  mutate(
    ref = sub(">.*", "", change),
    alt = sub(".*>", "", change),
    type = case_when(
    	nchar(ref) == 1 & nchar(alt) == 1 ~ "SNP",
    	nchar(ref) < nchar(alt) ~ "INS",
    	nchar(ref) > nchar(alt) ~ "DEL",
    	TRUE ~ "Other"
    )
  )
```


# Genomes Sizes

## Reference

```{r}
seqinfo(bedpe$ref) |> 
	as_tibble(rownames="seqname") %>% select(seqname,seqlengths) |>
	arrange(desc(seqlengths)) |>
	knitr::kable()
```

## Query

```{r}
seqinfo(bedpe$query) |> 
	as_tibble(rownames="seqname") %>% 
	select(seqname,seqlengths) |>
	arrange(desc(seqlengths)) |>
	knitr::kable()
```



# Queries best mapping

For each query, determine the reference sequence it covers most.

```{r}
	aln <- readGAlignments(params$bam_file,use.names=TRUE)
	best_qry_hits <- split(aln,names(aln)) |> 
		lapply(\(e) sum(coverage(e)>0)) |>
		enframe(name="query_id") |>
		unnest_longer(value,indices_to="ref_id",values_to="coverage") |>
		group_by(query_id) |>
		slice_max(coverage,n=1,with_ties=FALSE) |>
		arrange(desc(coverage)) %>% 
		left_join(seqinfo(bedpe$ref) %>% as_tibble(rownames="seqname") %>% select(ref_id=seqname,ref_len=seqlengths),by="ref_id") %>% 
		left_join(seqinfo(bedpe$query) %>% as_tibble(rownames="seqname") %>% select(query_id=seqname,query_len=seqlengths),by="query_id") %>% 
		relocate(query_id,best_ref_hit=ref_id,query_len,ref_len,coverage)
	
	best_qry_hits |>
		knitr::kable()
```



# BAM alignment overview

```{r}
#| fig-height: 16
#| fig-width: 16
as_tibble(bedpe) |>
	select(-ref.width,-query.width) |>
	ggplot(aes(
		x = ref.start,
		xend = ref.end,
		y = if_else(query.strand=="-",query.end,query.start),
		yend = if_else(query.strand=="-",query.start,query.end)
	)) + 
		facet_grid(query.seqnames~ref.seqnames,space="free",scales="free") +
		scale_x_continuous(labels = scales::label_number(scale_cut=scales::cut_short_scale())) +
		scale_y_continuous(labels = scales::label_number(scale_cut=scales::cut_short_scale())) +
		geom_segment() +
		theme_bw() + 
		theme(panel.spacing = unit(0,"mm")) +
		theme(strip.text.y = element_text(angle=0)) +
		xlab("Reference") + ylab("Query")
```












```{r}
#| fig-height: 16
#| fig-width: 16

bedpe_meta <- tibble(
	aln_idx = bedpe$aln_idx,
	ref_seq = as.factor(seqnames(bedpe$ref)),
	qry_seq = as.factor(seqnames(bedpe$query))
)
ggplot() + 
	facet_grid(qry_seq~ref_seq,scales="free_x",space="free_x") +
	geom_polygon(aes(x=value,y=source,group=aln_idx),fill="lightgrey",color="black",data=bedpePolygons(bedpe) |> left_join(bedpe_meta,by="aln_idx")) +
	geom_segment(aes(x=1,xend=seqlengths,y="ref",yend="ref"),linewidth = 2,data = as_tibble(seqinfo(bedpe$ref),rownames="ref_seq")) +
	geom_segment(aes(x=1,xend=seqlengths,y="qry",yend="qry"),linewidth = 2,data = as_tibble(seqinfo(bedpe$query),rownames="qry_seq")) +
	geom_jitter(aes(y="ref",x=pos+1L),data = muts |> dplyr::rename(ref_seq=chrom),color="red",width=0,height=0.03) +
	theme_bw() + 
	xlab("Position on Reference Genome") + ylab("")
```

## Gaps

### Reference gaps

```{r}
local({
	ref_gaps <- gaps(bedpe$ref,ignore.strand=TRUE)
	tibble(
		pos = as.character(ref_gaps),
		width = width(ref_gaps)
	)
}) |>
	knitr::kable()
```

### Query gaps

```{r}
local({
	qry_gaps <- gaps(bedpe$query,ignore.strand=TRUE)
	tibble(
		pos = as.character(qry_gaps),
		width = width(qry_gaps)
	)
}) |>
	knitr::kable()
```

# Mutations

## Summary

```{r mut_summary}
muts |>
	group_by("Mutation type"=type) |>
	dplyr::count() |>
	knitr::kable()
```

## Mutations per contig

```{r mut_barplot, fig.width=8, fig.height=4}
muts |>
  dplyr::count(chrom, type) |>
  ggplot(aes(x = chrom, y = n, fill = type)) +
    geom_col() +
    labs(x = "Contig", y = "Count", fill = "Type") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
```
